exempt_pcat = [
'Printing Supplies',
'Refrigerators',
'Laundry',
'Ovens',
'Water Heaters',
'Ice Machines',
'Condensing Units',
'Safety Storage',
'Dishwashers',
'Shower Doors, Tubs &Enclosures',
'Banquet Furniture',
'Trucks & Carts',
'Compact Appliances',
'Standard Vertical Blinds',
'Deluxe Vertical Blinds',
'Microwaves',
'Bellman\'s Carts & Accessories',
'Pre-hung Int. Doors',
'Bypass Doors',
'Exterior Doors',
'Slab Doors'
]
